# Generated by Django 2.2 on 2019-05-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': 'member', 'verbose_name_plural': 'member'},
        ),
    ]
