# Generated by Django 2.2 on 2019-04-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('department_id', models.IntegerField()),
                ('allocated_time', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('reg_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='doctors/')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
    ]
